FROM php:8.1-apache

# Set working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Apache config for CodeIgniter
RUN a2enmod rewrite
COPY ./docker/apache-config.conf /etc/apache2/sites-available/000-default.conf

# Copy existing application directory
COPY . /var/www/html

# Ensure appropriate permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80